# Generated by Django 4.2.14 on 2026-04-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('es_top', models.BooleanField(default=False)),
                ('estado', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Marcas',
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('contacto', models.CharField(blank=True, max_length=120, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Roles',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=60)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='catalogos.rol')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'db_table': 'usuarios',
            },
        ),
    ]
