# Generated by Django 4.2.14 on 2026-04-17 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_producto_movimientoinventario_inventario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('tabla_afectada', models.CharField(max_length=100)),
                ('registro_afectado_id', models.IntegerField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField()),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Bitacora',
                'db_table': 'bitacora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle_venta', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'detalles_venta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(max_length=30)),
                ('estado_venta', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_usuario_fk',
            field=models.ForeignKey(blank=True, db_column='id_usuario_fk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.usuario'),
        ),
    ]
