-- ============================================================
-- 02_schema.sql
-- Esquema del sistema de ventas e inventario (cosmetica)
-- ============================================================

-- Limpieza para re-ejecuciones
DROP TABLE IF EXISTS bitacora CASCADE;
DROP TABLE IF EXISTS envios CASCADE;
DROP TABLE IF EXISTS detalles_venta CASCADE;
DROP TABLE IF EXISTS ventas CASCADE;
DROP TABLE IF EXISTS detalles_compra CASCADE;
DROP TABLE IF EXISTS compras CASCADE;
DROP TABLE IF EXISTS movimientos_inventario CASCADE;
DROP TABLE IF EXISTS inventario CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS usuarios CASCADE;
DROP TABLE IF EXISTS marcas CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS favoritos CASCADE;

-- FASE 1: Configuracion y catalogos
CREATE TABLE roles (
    id_rol INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(50) NOT NULL UNIQUE,
    descripcion TEXT
);

CREATE TABLE categorias (
    id_categoria INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    descripcion TEXT,
    estado VARCHAR(20) NOT NULL
);

CREATE TABLE marcas (
    id_marca INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL UNIQUE,
    estado VARCHAR(20) NOT NULL
);

-- FASE 2: Actores del sistema
CREATE TABLE usuarios (
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol INTEGER NOT NULL,
    nombre_completo VARCHAR(150) NOT NULL,
    username VARCHAR(60) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    estado VARCHAR(20) NOT NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_usuarios_roles
        FOREIGN KEY (id_rol) REFERENCES roles(id_rol)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE TABLE clientes (
    id_cliente INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_completo VARCHAR(150) NOT NULL,
    telefono VARCHAR(25),
    ciudad VARCHAR(100),
    direccion TEXT,
    es_top BOOLEAN NOT NULL DEFAULT FALSE,
    estado VARCHAR(20) NOT NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    id_usuario_fk INTEGER NULL,
    CONSTRAINT fk_clientes_usuarios
        FOREIGN KEY (id_usuario_fk) REFERENCES usuarios(id_usuario)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

CREATE TABLE favoritos (
    id_favorito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,

    CONSTRAINT fk_favoritos_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios(id_usuario),

    CONSTRAINT fk_favoritos_producto
        FOREIGN KEY (id_producto)
        REFERENCES productos(id_producto),

    CONSTRAINT uq_favoritos_usuario_producto
        UNIQUE (id_usuario, id_producto)
);
CREATE TABLE proveedores (
    id_proveedor INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_empresa VARCHAR(150) NOT NULL,
    contacto VARCHAR(120),
    telefono VARCHAR(25),
    estado VARCHAR(20) NOT NULL
);

-- FASE 3: Core del negocio
CREATE TABLE productos (
    id_producto INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria INTEGER NOT NULL,
    id_marca INTEGER NOT NULL,
    nombre VARCHAR(150) NOT NULL,
    descripcion TEXT,
    precio_compra NUMERIC(12,2) NOT NULL,
    precio_venta NUMERIC(12,2) NOT NULL,
    atributos JSONB NOT NULL DEFAULT '{}'::jsonb,
    estado VARCHAR(20) NOT NULL,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_productos_categorias
        FOREIGN KEY (id_categoria) REFERENCES categorias(id_categoria)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_productos_marcas
        FOREIGN KEY (id_marca) REFERENCES marcas(id_marca)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_precios_producto
        CHECK (precio_compra >= 0 AND precio_venta >= 0)
);

CREATE TABLE inventario (
    id_inventario INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL UNIQUE,
    stock_actual INTEGER NOT NULL,
    stock_minimo INTEGER NOT NULL,
    ultima_actualizacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_inventario_productos
        FOREIGN KEY (id_producto) REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_stock_inventario
        CHECK (stock_actual >= 0 AND stock_minimo >= 0)
);

CREATE TABLE movimientos_inventario (
    id_movimiento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_producto INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    tipo_movimiento VARCHAR(20) NOT NULL,
    cantidad INTEGER NOT NULL,
    fecha_movimiento TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    motivo VARCHAR(200),
    CONSTRAINT fk_movinv_productos
        FOREIGN KEY (id_producto) REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_movinv_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_cantidad_movimiento
        CHECK (cantidad > 0)
);

-- FASE 4: Transacciones
CREATE TABLE compras (
    id_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_proveedor INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_compra TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto_total NUMERIC(12,2) NOT NULL,
    estado_compra VARCHAR(20) NOT NULL,
    CONSTRAINT fk_compras_proveedores
        FOREIGN KEY (id_proveedor) REFERENCES proveedores(id_proveedor)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_compras_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_monto_total_compra
        CHECK (monto_total >= 0)
);

CREATE TABLE detalles_compra (
    id_detalle_compra INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_compra INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    lote VARCHAR(50),
    fecha_vencimiento DATE,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_detcomp_compras
        FOREIGN KEY (id_compra) REFERENCES compras(id_compra)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_detcomp_productos
        FOREIGN KEY (id_producto) REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_detalle_compra
        CHECK (cantidad > 0 AND precio_unitario >= 0 AND subtotal >= 0)
);

CREATE TABLE ventas (
    id_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL,
    id_usuario INTEGER NOT NULL,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    monto_total NUMERIC(12,2) NOT NULL,
    metodo_pago VARCHAR(30) NOT NULL,
    estado_venta VARCHAR(30) NOT NULL,
    monto_recibido NUMERIC(12,2),
    vuelto NUMERIC(12,2),
    numero_comprobante VARCHAR(100),
    imagen_qr_url VARCHAR(255),
    CONSTRAINT fk_ventas_clientes
        FOREIGN KEY (id_cliente) REFERENCES clientes(id_cliente)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT fk_ventas_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_monto_total_venta
        CHECK (monto_total >= 0)
);

CREATE TABLE detalles_venta (
    id_detalle_venta INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL,
    id_producto INTEGER NOT NULL,
    cantidad INTEGER NOT NULL,
    precio_unitario NUMERIC(12,2) NOT NULL,
    subtotal NUMERIC(12,2) NOT NULL,
    CONSTRAINT fk_detven_ventas
        FOREIGN KEY (id_venta) REFERENCES ventas(id_venta)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_detven_productos
        FOREIGN KEY (id_producto) REFERENCES productos(id_producto)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,
    CONSTRAINT chk_detalle_venta
        CHECK (cantidad > 0 AND precio_unitario >= 0 AND subtotal >= 0)
);

CREATE TABLE envios (
    id_envio INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL UNIQUE,
    tipo_envio VARCHAR(30) NOT NULL,
    empresa_transporte VARCHAR(100),
    estado_envio VARCHAR(20) NOT NULL,
    CONSTRAINT fk_envios_ventas
        FOREIGN KEY (id_venta) REFERENCES ventas(id_venta)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- FASE 5: Seguridad
CREATE TABLE bitacora (
    id_bitacora INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    accion VARCHAR(50) NOT NULL,
    tabla_afectada VARCHAR(100) NOT NULL,
    registro_afectado_id INTEGER,
    detalle TEXT,
    fecha_hora TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    direccion_ip VARCHAR(45),
    CONSTRAINT fk_bitacora_usuarios
        FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);
