-- ============================================================
-- 08_migracion_pedidos_guardados.sql
-- Crea tablas para carritos/pedidos guardados por clientes.
-- No reserva stock; solo guarda productos y cantidades.
-- Idempotente: se puede correr multiples veces sin error.
-- ============================================================

CREATE TABLE IF NOT EXISTS pedidos_guardados (
    id_pedido_guardado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_cliente INTEGER NOT NULL REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    nombre VARCHAR(120) NOT NULL,
    creado_en TIMESTAMP NOT NULL DEFAULT NOW(),
    actualizado_en TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS detalles_pedido_guardado (
    id_detalle_pedido_guardado INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pedido_guardado INTEGER NOT NULL REFERENCES pedidos_guardados(id_pedido_guardado) ON DELETE CASCADE,
    id_producto INTEGER NOT NULL REFERENCES productos(id_producto) ON DELETE RESTRICT,
    cantidad INTEGER NOT NULL CHECK (cantidad > 0)
);

CREATE INDEX IF NOT EXISTS idx_pedidos_guardados_cliente
    ON pedidos_guardados(id_cliente);

CREATE INDEX IF NOT EXISTS idx_detalles_pedido_guardado_pedido
    ON detalles_pedido_guardado(id_pedido_guardado);
