-- ============================================================
-- 09_migracion_pago_transacciones.sql
-- Crea tabla de trazabilidad para transacciones de pago.
-- Idempotente para bases existentes.
-- ============================================================

CREATE TABLE IF NOT EXISTS pagos_transacciones (
    id_pago_transaccion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_venta INTEGER NOT NULL,
    proveedor VARCHAR(30) NOT NULL DEFAULT 'manual',
    estado_pago VARCHAR(30) NOT NULL,
    monto NUMERIC(12,2) NOT NULL DEFAULT 0,
    moneda VARCHAR(10) NOT NULL DEFAULT 'BOB',
    id_transaccion_externa VARCHAR(120),
    idempotency_key VARCHAR(120),
    evento_webhook_id VARCHAR(120),
    detalle TEXT,
    creado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_en TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pago_tx_venta
        FOREIGN KEY (id_venta) REFERENCES ventas(id_venta)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT chk_pago_tx_monto_nonneg
        CHECK (monto >= 0)
);

CREATE INDEX IF NOT EXISTS idx_pagos_tx_id_venta
    ON pagos_transacciones(id_venta);

CREATE INDEX IF NOT EXISTS idx_pagos_tx_estado
    ON pagos_transacciones(estado_pago);

CREATE UNIQUE INDEX IF NOT EXISTS ux_pagos_tx_idempotency
    ON pagos_transacciones(idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS ux_pagos_tx_evento_webhook
    ON pagos_transacciones(evento_webhook_id)
    WHERE evento_webhook_id IS NOT NULL;
