-- ============================================================
-- 11_migracion_favoritos.sql
-- Agrega soporte de favoritos para la tienda publica.
-- Idempotente: se puede correr multiples veces sin error.
-- ============================================================

-- Rol Cliente usado por registro/login de tienda.
INSERT INTO roles (id_rol, nombre_rol, descripcion)
VALUES (6, 'Cliente', 'Cliente final que compra en la tienda online.')
ON CONFLICT (id_rol) DO NOTHING;

SELECT setval(
    pg_get_serial_sequence('roles', 'id_rol'),
    GREATEST((SELECT MAX(id_rol) FROM roles), 6)
);

-- Campo opcional usado por serializers/perfil.
ALTER TABLE usuarios
    ADD COLUMN IF NOT EXISTS descripcion TEXT;

-- Vinculo cliente <-> usuario para clientes registrados desde la tienda.
ALTER TABLE clientes
    ADD COLUMN IF NOT EXISTS id_usuario_fk INTEGER NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_clientes_usuarios'
    ) THEN
        ALTER TABLE clientes
            ADD CONSTRAINT fk_clientes_usuarios
            FOREIGN KEY (id_usuario_fk)
            REFERENCES usuarios(id_usuario)
            ON UPDATE CASCADE
            ON DELETE SET NULL;
    END IF;
END $$;

-- Tabla principal de favoritos.
CREATE TABLE IF NOT EXISTS favoritos (
    id_favorito INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INTEGER NOT NULL,
    id_producto INTEGER NOT NULL
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_favoritos_usuario'
    ) THEN
        ALTER TABLE favoritos
            ADD CONSTRAINT fk_favoritos_usuario
            FOREIGN KEY (id_usuario)
            REFERENCES usuarios(id_usuario)
            ON UPDATE CASCADE
            ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_favoritos_producto'
    ) THEN
        ALTER TABLE favoritos
            ADD CONSTRAINT fk_favoritos_producto
            FOREIGN KEY (id_producto)
            REFERENCES productos(id_producto)
            ON UPDATE CASCADE
            ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'uq_favoritos_usuario_producto'
    ) THEN
        ALTER TABLE favoritos
            ADD CONSTRAINT uq_favoritos_usuario_producto
            UNIQUE (id_usuario, id_producto);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_favoritos_usuario
    ON favoritos (id_usuario);

CREATE INDEX IF NOT EXISTS idx_favoritos_producto
    ON favoritos (id_producto);
